from langchain_google_genai import ChatGoogleGenerativeAI
from utils.utils import get_api_key

def refine_description(description: str):
    model = ChatGoogleGenerativeAI(
        model = "gemini-2.0-flash",
        google_api_key = get_api_key("google_api_key")
    )

    prompt = f"""
    You are an expert editor and information refiner, tasked with refining descriptions generated by a Vision Language model.
    Your goal is to make the descriptions more accurate, and **crucially, highly relevant for further processing by another AI agent.**

    Here is the initial description:
    "{description}"

    """

    prompt += """
    Please provide a refined version of the description, focusing on:
    - **Extracting and highlighting the core subject and key details.**
    - **Ensuring the description is factual and concise.**
    - **Removing any unnecessary or ambiguous language.**
    - **Making the description clear and unambiguous for another AI agent to understand.**
    - Clarity and conciseness.
    - Suitability for an Instagram audience.
    - Correcting any factual errors.

    Refined Description (Focus on key information for another AI agent):
    """
    try:
        response = model.invoke(prompt)
        refined_description = response.content.strip()
        return refined_description
    except:
        pass